Feature/login/initial
White-Diamond/OCTOGON pull request #18
Opened 2021-04-01 23:25 UTC by rkline2

This code consists of the user login/sign up page. Both implementations are located in a single html file. There's also another html file that consists of the password recovery page. 

This is front-end code only and still requires back-end maintenance to achieve full functionality.

2021-04-01 23:33 UTC, Squirrelofudun requested changes
icon.png needs to be added, and main.js needs to be fixed/removed

2021-04-01 23:33 UTC, Squirrelofudun commented on Octogon_Login/pswrd_recv.html
> +  <link rel="apple-touch-icon" href="icon.png">
icon.png doesn't currently exist.

2021-04-01 23:33 UTC, Squirrelofudun commented on Octogon_Login/pswrd_recv.html
> +  <script src="js/main.js"></script>
main.js throws an error

2021-04-02 17:53 UTC, rkline2 commented on Octogon_Login/pswrd_recv.html
> +  <link rel="apple-touch-icon" href="icon.png">
Okay sounds good. Issue is fixed

2021-04-02 17:53 UTC, rkline2 commented on Octogon_Login/pswrd_recv.html
> +  <script src="js/main.js"></script>
Okay sounds good. Issue is fixed

2021-04-02 22:01 UTC, closed without merging